name: pigallery2_android
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  provider: ^6.0.3
  photo_view:
    git:
      url: https://github.com/Lakjdf/photo_view.git
  shared_preferences: ^2.0.15
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  mime: ^1.0.2
  better_player: ^0.0.83
  flutter_secure_storage: ^5.0.2
  flutter_inappwebview: ^6.0.0-beta.22
  path_provider: ^2.0.12
  share_plus: ^6.3.1
  collection: ^1.16.0
  dynamic_color: ^1.6.3
  backdrop:
    git:
      url: https://github.com/Lakjdf/backdrop.git
  
  # file selector dialog to download media:
  # flutter_plugin_android_lifecycle: ^2.0.1
  # file_selector_platform_interface: ^2.4.0
  # file_selector_android:
  #   git:
  #     url: https://github.com/southworks/plugins.git
  #     ref: 9082aaf4336880db6a40458d2e502b86bcff453c
  #     path: packages/file_selector/file_selector_android

dev_dependencies:
  # app icon generation; does not work for Android 12
  # run: flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: "^0.9.3"

    # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# app icon generation (flutter_launcher_icons config)
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon_inv.png"


flutter:
  uses-material-design: true