name: pigallery2_android
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  provider: ^6.1.1
  photo_view:
    git:
      url: https://github.com/Lakjdf/photo_view.git
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  mime: ^1.0.5
  better_player: ^0.0.83
  flutter_secure_storage: ^5.1.2
  flutter_inappwebview: ^6.0.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  collection: ^1.18.0
  dynamic_color: ^1.6.9
  backdrop:
    git:
      url: https://github.com/Lakjdf/backdrop.git
  path: ^1.8.3
  async: ^2.11.0
  intl: ^0.19.0
  ionicons: ^0.2.2
  flutter_cache_manager: ^3.3.1
  motion_photos: ^0.0.3
  quiver: ^3.2.1
  
  # file selector dialog to download media:
  # flutter_plugin_android_lifecycle: ^2.0.1
  # file_selector_platform_interface: ^2.4.0
  # file_selector_android:
  #   git:
  #     url: https://github.com/southworks/plugins.git
  #     ref: 9082aaf4336880db6a40458d2e502b86bcff453c
  #     path: packages/file_selector/file_selector_android

dependency_overrides:
  # Can be removed when
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203 is merged.
  wakelock_windows:
    git:
      url: https://github.com/diegotori/wakelock
      ref: 40464c75e908f57f458597ef4912f5273ab89b1a
      path: wakelock_windows

dev_dependencies:
  # app icon generation; does not work for Android 12
  # run: flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: "^0.9.3"

    # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# app icon generation (flutter_launcher_icons config)
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon_inv.png"


flutter:
  uses-material-design: true