name: pigallery2_android
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  provider: ^6.1.2

  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  collection: ^1.18.0
  quiver: ^3.2.2
  path: ^1.9.0
  async: ^2.11.0
  intl: ^0.20.1
  logging: ^1.3.0
  mutex: ^3.1.0
  mime: ^2.0.0

  dynamic_color: ^1.7.0
  share_plus: ^10.1.2
  motion_photos: ^1.0.0

  photo_view:
    git:
      url: https://github.com/Lakjdf/photo_view.git
  media_kit: ^1.1.11
  media_kit_video: ^1.2.4
  media_kit_libs_android_video: ^1.3.6

  backdrop:
    git:
      url: https://github.com/Lakjdf/backdrop.git
  flutter_inappwebview: ^6.1.5
  visibility_detector: ^0.4.0+2

  flutter_spinkit: ^5.2.1
  ionicons: ^0.2.2

  # file selector dialog to download media:
  # flutter_plugin_android_lifecycle: ^2.0.1
  # file_selector_platform_interface: ^2.4.0
  # file_selector_android:
  #   git:
  #     url: https://github.com/southworks/plugins.git
  #     ref: 9082aaf4336880db6a40458d2e502b86bcff453c
  #     path: packages/file_selector/file_selector_android

dev_dependencies:
  # app icon generation; does not work for Android 12
  # run: flutter pub run flutter_launcher_icons:main
#  flutter_launcher_icons: "^0.9.3"

    # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# app icon generation (flutter_launcher_icons config)
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon_inv.png"


flutter:
  uses-material-design: true