name: Create Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Get Packages
        run: flutter pub get
        
      - name: Build APK
        run: |
          VERSION_NAME=${GITHUB_REF_NAME#v}
          VERSION_CODE=${VERSION_NAME//.}
          echo "Version: $VERSION_NAME ($VERSION_CODE)"
          flutter build apk --split-per-abi --release --enable-experiment=records --build-name=$VERSION_NAME --build-number=$VERSION_CODE
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
